### ISSUE TITLE
Regression in Commit 7312421: Download Failure

### ISSUE THREAD

**Issue by MasonSchleider** [makehumancommunity/community-plugins-assetdownload#11]
System: Windows 7 64-bit
MakeHuman Version: 1.1.1

A bug introduced in commit [7312421](https://github.com/makehumancommunity/community-plugins-assetdownload/commit/73124210b4ccc87eb75dd02c8a92ded512f4de14) causes an exception when attempting to download files.

The exception is caused by the 'isnumeric' method call on line 102. The 'isnumeric' method is only present on unicode objects. It is not present on string objects.

I fixed this by replacing 'str()' with 'unicode()'.

**Comment by joepal1976** [comment]
Ok, thanks for pointing this out.

I'm currently developing mostly for py3, for which the construct is perfectly valid (as all strings are unicode to begin with in py3). I'll make a workaround for py2 too. 

As a side note: at some point, I'll stop trying to maintain py2 backwards compatibility. But this won't happen until version 1.2.0 of MakeHuman is released.
