### ISSUE TITLE
Py3 version does not seem to download MHCLO

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/community-plugins-assetdownload#2]
From http://www.makehumancommunity.org/forum/viewtopic.php?f=3&t=14665

This is probably specific to py3 as no-one complained about it when using the asset downloader with the stable release.

**Comment by robertltux** [comment]
yes same assets are correct when using stable (sidebar also the caps/nocaps thing is getting to be a pain in finding assets in the list)

**Comment by joepal1976** [comment]
Works after big refactor (which is basically a rewrite from scratch).
