### ISSUE TITLE
Node ID search capability

### ISSUE THREAD

**Issue by rwbaer** [makehumancommunity/community-plugins-assetdownload#20]
This forum post lists some specific assets that produce problems on download: http://www.makehumancommunity.org/forum/viewtopic.php?f=3&t=17111&p=47490#p47481

In trying to reproduce the problem (see that thread for Exception details of the problem itself), I realized it was difficult to find an asset from it's node ID in the asset downloader.  There is no global search. You must pick a specific asset type.  If you sort by node ID, it does an alpha sort not a numeric sort.

Two feature requests:
1) be able to search for a node globally.
2) Set Node ID to sort numerically, not alpha (or is this just Windows?)

**Comment by joepal1976** [comment]
Yeah, I ran into the same problem when trying to debug the issue. 

It's would be useful for debugging, but there is a workaround for now. You can browse to the asset by node ID by going to http://www.makehumancommunity.org/node/[id]. This will show the asset in question and give you an indication of what type of asset it is.

**Comment by joepal1976** [comment]
Not going to do anything about this for now
