### ISSUE TITLE
Asset Downloader Misplaces Some Materials

### ISSUE THREAD

**Issue by MTKnife** [makehumancommunity/community-plugins-assetdownload#21]
For some but not all materials, the asset downloader places the material files in the master "materials" directory rather than in the directories of the matching assets.  For example, one recent asset is placed in the directory "clothes/Elvs_Male_Kilt_1"; a material for it is placed in "materials/Plaid_kilt_texture1"--despite the fact that the material is properly registered to the clothes in the database.

I've attached a list of the directories in my "materials" directory, though of course some of the materials will have been placed there because they're not properly paired with their associated assets.
[mats.txt](https://github.com/makehumancommunity/community-plugins-assetdownload/files/3046381/mats.txt)

**Comment by joepal1976** [comment]
Well, there was a very easy explanation for the problem. The relevant code is as follows:

    if "belongs_to_id" in self.belongs_to_metadata:
        # TODO: It should be possible to match material directories for third part assets too
        self.log.trace("Belongs to id")

... so the functionality for matchine third-part materials with third-part assets isn't even implemented. 

I thought I had done that...

**Comment by joepal1976** [comment]
I have a potential fix for this commited to master now. It works with with the elvs kilt mentioned above, but could use more testing before I close the issue.

**Comment by MTKnife** [comment]
At the moment, I'm running the compiled version of Alpha 3--I assume I'd have to download the source of the main app in order to use the source of the plug-in?  I'll see if I can manage that Tuesday night.

**Comment by Aranuvir** [comment]
You just have to replace the content of the 8_asset_downloader folder and delete the __pycache__ folder...

**Comment by MTKnife** [comment]
Yes, that seems to work.  Thanks!

**Comment by Aranuvir** [comment]
Seems to be fixed. Closing.
