### ISSUE TITLE
File path error with node id 67 slave collar full metal

### ISSUE THREAD

**Issue by yumri4** [makehumancommunity/community-plugins-assetdownload#25]
Makehuman 1.2.0 alpha 4 works fine until I use the community asset Node id 67 author learning license CC0 title Salve collar full metal. When I use that asset I get the error 
`Cannot get texture for file path Tileable+eroded+scratch+metal+background+05.jpg. no such file.`
In the Logs tab under Utilities. It goes away when the asset is removed.  It happens even if the process is repeated with a reset of the 3D model then the Salve collar full metal is applied. In that I concluded it is that asset. 

Please fix.

**Comment by Aranuvir** [comment]
The issue is within the asset itself. Its a problem with the texture filename in the mhmat file. We do not fix user contributed assets. You can either fix it on your own or make a request here: http://www.makehumancommunity.org/forum/viewforum.php?f=20
