### ISSUE TITLE
Import MHX2 error

### ISSUE THREAD

**Issue by David-M-Kelly** [makehumancommunity/community-plugins-assetdownload#27]
Hi

When I try to import a particular character into Blender I get an error message and the character fails to import.

Opening MHX2 file b'E:\\Shared\\3D\\MakeHuman models\\Hype05A.mhx2'
Creating CYCLES material Hype05a:Female_muscle_13442:Young_asian_female
Creating CYCLES material Hype05a:High-poly:Sapphirecateyes
Creating CYCLES material Hype05a:Teeth_base:Teethmaterial
Creating CYCLES material Hype05a:Tongue01:Tongue01material
Creating CYCLES material Hype05a:Bodysuit:Zerosuitmat
Traceback (most recent call last):
  File "C:\Users\david\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\import_runtime_mhx2\importer.py", line 56, in execute
    importMhx2File(self.filepath, cfg, context)
  File "C:\Users\david\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\import_runtime_mhx2\importer.py", line 144, in importMhx2File
    build(struct, cfg, context)
  File "C:\Users\david\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\import_runtime_mhx2\importer.py", line 201, in build
    mname,mat = buildMaterial(mhMaterial, scn, cfg)
  File "C:\Users\david\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\import_runtime_mhx2\materials.py", line 40, in buildMaterial
    buildMaterialCycles(mat, mhMaterial, scn, cfg)
  File "C:\Users\david\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\import_runtime_mhx2\materials.py", line 159, in buildMaterialCycles
    normalTex.color_space = 'NONE'
AttributeError: 'ShaderNodeTexImage' object has no attribute 'color_space'

location: <unknown location>:-1

location: <unknown location>:-1

Details

MH 1.2.0a3
Blender 2.82a
Windows 10

Base character with Skintight Body Suit (Female) by TioMegamanX id 1604

Thanks!

**Comment by Aranuvir** [comment]
You're using an outdated version of MHX2 and that's the wrong repo for issues with MHX. For general question about the usage of MakeHuman's software, please ask in the forum. Here is the bug tracker, not the help desk.

**Comment by David-M-Kelly** [comment]
Nice and friendly... It throws up an error. The website provides a link to this location for reporting errors, so I followed it.

**Comment by joepal1976** [comment]
For your particular problem, try downloading the latest blender-side version of MHX here: http://www.makehumancommunity.org/content/plugins.html

If the problem persist, please make a bug report in the MHX issue tracker at https://github.com/makehumancommunity/mhx2-makehuman-exchange/issues

If a page on the main site led you here for posting bugs regarding MHX, I'll need to fix that as this is the issue tracker for the asset downloader, not for MHX. On which page did you find the link?

**Comment by David-M-Kelly** [comment]
Thank you

**Comment by David-M-Kelly** [comment]
Apologies, it looks like I clicked on the asset tracker bugtracker link rather than the makehuman one by mistake.

 
 

Sent: Tuesday, May 05, 2020 at 8:12 AM
