### ISSUE TITLE
Large thumbnails scramble the layout

### ISSUE THREAD

**Issue by Aranuvir** [makehumancommunity/community-plugins-assetdownload#8]
Some assets have large thumbnails, like Mindfront's F Dress 06 or M Suit 01 (1080x1080). These images are scaled incorrectly in the plug in and shift the layout:
![asset_download](https://user-images.githubusercontent.com/23557933/34079427-d8b0d1b4-e32d-11e7-82dd-4ac6952bff05.jpeg)

**Comment by joepal1976** [comment]
Ok. I guess I should set the image to a fixed pixel size instead of trusting that people followed instructions when uploading .thumb files.

**Comment by Aranuvir** [comment]
Cannot reproduce, obviously fixed...
