### ISSUE TITLE
Table sorting does not work.

### ISSUE THREAD

**Issue by Aranuvir** [makehumancommunity/community-plugins-assetdownload#9]
To reproduce: Select an asset type, e.g. clothes and update list. In the topwidget table click on an field to sort, e.g. "author" to sort the asset list by author names. Now select an asset e.g. Joe's crude femal t-shirt, result: a different asset than the selected is displayed.

**Comment by joepal1976** [comment]
Ouch. Good catch though. I obviously did not test that.

**Comment by joepal1976** [comment]
Further comment from rob:

> Windows 10 mh 1.2.0 a2
> 
> Sorry if this is a dup. I thought there was an issue for something similar but couldn't find it ...
> 
> Tried to download 599 1731 after sorting clothes list by name.
> Got fluffy tail rather than margaret Toigo "Skirt with Lace Ruffle" Fluffy tail is 405 1193.
